sudo: required
services:
  - docker

before_install:
  - docker build -t smartdockerimage/fib-app -f ./client/Dockerfile.dev ./client

script:
  - docker run smartdockerimage/fib-app npm test -- --coverage

after_success:
  - docker build -t smartdockerimage/fib-client ./client
  - docker build -t smartdockerimage/fib-nginx ./nginx
  - docker build -t smartdockerimage/fib-server ./server
  - docker build -t smartdockerimage/fib-worker ./worker
  # Login to your docker account
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push your images to docker hub
  - docker push smartdockerimage/fib-client
  - docker push smartdockerimage/fib-nginx
  - docker push smartdockerimage/fib-server
  - docker push smartdockerimage/fib-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-1
  app: multi-docker-app
  env: MultiDockerApp-env
  # For buckect_name type s3 in services to copy bucket name of your current app
  bucket_name: elasticbeanstalk-us-east-1-441154321604
  # For bucket_path, "app" above is the same as the bucket_path
  bucket_path: multi-docker-app
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY