FROM node:alpine
WORKDIR "/app"
COPY ./package.json ./
RUN npm install
COPY . .
CMD ["npm", "run", "dev"]"option_settings" :
       [
         {
          "Namespace": "aws:elasticbeanstalk:command",
          "OptionName": "Timeout",
          "Value": "3600"
         }
       ]